### PR TITLE
add code to generate radar plots 

### PR DESCRIPTION
**Pull request by matthieufaillot**
display disconnection of corticocortical, corticostriatal, corticothalamic for ANTS and FSL cavities
each radar plots displays behavioral data (peroperative verbal perseveration "en boucle", verbal perseveration early postop, verbal perseveration late postop)

### CODE REVIEW

**Review by bthirion — COMMENTED** [review]
There are a bunch of details (violations of official Python syntactic rules), but this is not super important ---as long as the code runs. We can fix that later.

My main comment is that we should probably not commit the two png files, as they are not generated by the script anyhow. Do you agree on that ?

Best,

**Comment by bthirion** [comment]
Also, there are some redundancies in the plotting code, that could be refactorized. But again, thsi can be done later.

**Comment by bthirion** [comment]
I can rerun the code, so we're fine.

I you can remove the two png files, I'll be happy to merge the PR !

**Comment by matthieufaillot** [comment]
Thank you !
I removed the file from my local repo and  made a new commit

**Comment by bthirion** [comment]
Great, merging.

**Pull request merged**
